src/VSTheWorld/Controllers/Web/AppController.cs
using System.Linq;
using Microsoft.AspNet.Mvc;
using VSTheWorld.ViewModels;
using VSTheWorld.Services;
using VSTheWorld.Models;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace VSTheWorld.Controllers.Web
{
    public class AppController : Controller
    {
        private IMailService _mailService;
        private IWorldRepository _repository;

        public AppController(IMailService service, IWorldRepository repository)
        {
            // Constructor for injection
            _mailService = service;
            _repository = repository;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            var trips = _repository.GetAllTrips();

            // pass trips into the View.  The view will be able to read information from the Model.
            return View(trips);
		}
		public IActionResult About()
		{
			return View();
		}
		public IActionResult Contact()
		{
			return View();
		}

        [HttpPost]
        public IActionResult Contact(ContactViewModel model)
        {
            if (ModelState.IsValid) { 
                string email = Startup.Configuration["AppSettings:SiteEmailAddress"];

                if (string.IsNullOrWhiteSpace(email))
                {
                    ModelState.AddModelError("", "Could not send email.  Configuration issues exist on the server.  Contact the system administrator.");
                }

                if (_mailService.SendMail(email, email, $"Contact Page from {model.Name} ({model.Email}): {model.Subject}", model.Message))
                {
                    ModelState.Clear();
                    ViewBag.Message = "Mail sent.  Thanks!";
                }
            }

            return View();
        }
	}

}

src/VSTheWorld/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<title>The World - @ViewBag.Title</title>
	<meta charset="utf-8" />

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootswatch/yeti/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css" />
	<link rel="stylesheet" href="~/css/site.css" />
</head>



<body>
    <div id="sidebar">
		<img class="headshot" src="~/img/Bob.jpeg" alt="headshot" />
		<span id="username">Bob Holdings</span>
		<ul class="nav">
			<li class="active"><a asp-controller="App" asp-action="Index">Home</a></li>
			<li class="inactive"><a asp-controller="App" asp-action="About">About</a></li>
			<li class="inactive"><a asp-controller="App" asp-action="Contact">Contact</a></li>
		</ul>
	</div>
	<div id="mainwrapper" class="panel-body">
        <div id="topbar">
            <nav class="navbar navbar-inverse">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-xs-1">
                            <button id="toggleSidebar" class="btn btn-primary">
                                <i class="fa fa-angle-double-left"></i>
                            </button>
                        </div>
                        <div class="col-xs-8"> <a asp-controller="App" asp-action="Index" class="navbar-brand">The World</a></div>
                        <div class="col-xs-3">
                            <ul class="nav navbar-nav navbar-right">
                                <li>
                                    <a href="#" class="btn btn-sm btn-info">
                                        <i class="fa fa-save"></i> Save
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="btn btn-sm btn-info">
                                        <i class="fa fa-print"></i> Print
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </nav>
        </div>
        <div id="footer" class="container-fluid text-center bottom">
            <div class="navbar navbar-inverse navbar-fixed-bottom">
                <p class="text-info">&copy; 2016 JKing</p>
            </div>
        </div>
		<div id="main" class="container-fluid">
			<div id="mainbody">
				@RenderBody()
			</div>
		</div>
    </div>

	<script type="text/javascript" src="~/lib/jquery/dist/jquery.js"></script>
    <script type="text/javascript" src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="~/js/site.js"></script>
    
    @RenderSection("Scripts", false)
</body>
</html>